# azure-pipelines.yml

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo 'Building.................'

  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo 'Testing..'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: echo 'Deploying....'
